### ISSUE TITLE
Need sample for each device access

### ISSUE THREAD

**Issue by yboujraf** [LdB-ECM/linux_device_access#1]
Dear @LdB-ECM,

Is it possible to share in the read.me a sample code for each device access ?

- read
- write
- interrupt

I am interested for interrupt that means if any events occur then the raspberry PI4 will trigger an action.

Best Regards,
Youssef

**Comment by LdB-ECM** [comment]
The problem is for interrupts you will need to install a driver, you need a top and bottom handler for linux.
If you search the term "linux top and bottom handlers" you should get some useful links. As you will have
driver access you can get access to the hardware without going thru gpiomem at all both for speed and
security.
